openapi: 3.1.0
info:
  title: Static OpenAPI document of Smart Sentences Search resource
  description: Smart Search resources Open API documentation
  version: "1.0"

servers:
  - url: http://localhost:8080/q/openapi
    description: Optional dev mode server description

paths:
  /search:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchData'
      responses:
        200:
          description: new fruit resource created
          content:
            application/json: {}

components:
  schemas:
    SearchData:
      properties:
        search:
          type: string
        sentences:
          type: string